landmark_choices = {
    'a': 'Laney College',
    'b': 'UC Berkeley',
    'c': 'Oakland museum',
    'd': 'Uc San Francisco',
    'e': 'Alcatraz Island',
    'f': 'Lake Merritt/ Children fairyland',
    'g': 'chinatown',
    'h': 'Rockridg',
    'i': 'Cal State East Bay',
    'j': 'Museum of Main',
    'k': 'Chabot College',
    'l': 'Lena Toure',
    'm': 'Cal State East Bay-Concord Campus',
    'n': 'Diablo Costa College',
    'o': 'San Mateo County History Museum',
    'p': 'Colma Cemeteries',
    'q': 'Richmond Capitol Corridor Amtrak',
    'r': 'California Shakespeare Theatre Bruns Amphitheater',
    's': 'Los Medanos College',
    't': 'Adama toure',
    'u': 'Arlington Part',
    'v': 'Bayfair Center',
    'w': 'Amador Theater',
    'x': 'Hayward Japaness garden',
    'y': 'berkey bowl',
    'z': 'College Avenue'
}
