vc_landmarks = {
    'Laney College': set(['Lake Merritt']),
    'UC Berkeley': set(['Donwtown Berkeley']),
    'Oakland museum': set(['Lake Meritt']),
    'Uc San Francisco': set(['Civic Center']),
    'Alcatraz Island': set(['Embarcadero']),
    'Lake Merritt/ Children fairyland': set(['19th St/Oakland']),
    'chinatown': set(['12th St/Oakland City Center', 'Lake Merritt']),
    'Rockridg': set(['Rockridge']),
    'Cal State East Bay': set(['Hayward']),
    'Museum of Main': set(['Asby']),
    'Chabot College': set(['Hayward', 'South Hayward']),
    'Fremont Central Park/Lake Elizabeth': set(['Fremont']),
    'Cal State East Bay-Concord Campus': set(['Concord']),
    'Diablo Costa College': set(['El Cerrito del Norte']),
    'San Mateo County History Museum': set(['Millbrae']),
    'Colma Cemeteries': set(['Colma']),
    'Richmond Capitol Corridor Amtrak': set(['Richmond']),
    'California Shakespeare Theatre Bruns Amphitheater': set(['San Bruno']),
    'Los Medanos College': set(['Pleasant Hill/Contra Costa Centre']),
    'Adama toure': set(['MacArthur']),
    'Arlington Part': set(['Powell St']),
    'Bayfair Center': set(['Bay Fair']),
    'Amador Theater': set(['Dublin/Pleasanton']),
    'Hayward Japaness garden': set(['Hayward']),
    'berkey bowl': set(['Ashby']),
    'College Avenue': set(['Orinda'])
}
