vc_metro = {
    'Antioch': set(['Pittsburg Center']),
    'Pittsburg Center': set(['Antioch', 'Pittsburg Bay Point']),
    'Pittsburg Bay Point': set(['Pittsburg Center', 'North Concord Martinez']),
    'North Concord Martinez': set(['Pittsburg Bay Point', 'Concord']),
    'Concord': set(['North Concord Martinez', 'Pleasant Hill/Conta Costa Centre']),
    'Pleasant Hill/Conta Costa Centre': set(['Concord', 'Walnut Creek']),
    'Walnut Creek': set(['Pleasant Hill/Conta Costa Centre', 'Lafayette']),
    'Lafayette': set(['Walnut Creek', 'Orinda']),
    'Orinda': set(['Lafayette', 'MacArthur']),
    'MacArthur': set(['Lafayette', 'Orinda', 'Asby', '19th St/Oakland']),
    '19th St/Oakland': set(['MacArthur', '12th St/Oakland City Center']),
    '12th St/Oakland City Center': set(['19th St/Oakland', 'Lake Merritt', 'West Oakland']),
    'West Oakland': set(['12th St/Oakland City Center', 'Embarcadero']),
    'Embarcadero': set(['West Oakland', 'Montgomery St']),
    'Montgomery St': set(['Embarcadero', 'Powell St']),
    'Powell St': set(['Montgomery St', 'Civic Center/UN Plaza']),
    'Civic Center/UN Plaza': set(['Powell St', '16th St Mission']),
    '16th St Mission': set(['Civic Center/UN Plaza', '24th St Mission']),
    '24th St Mission': set(['16th St Mission', 'Glen Park']),
    'Glen Park': set(['24th St Mission', 'Daly City']),
    'Daly City': set(['Glen Park', 'Colma']),
    'Colma': set(['Daly City', 'South San Francisco']),
    'South San Francisco': set(['Colma', 'San Bruno']),
    'San Bruno': set(['South San Francisco', 'Millbrae', 'SFO Airport']),
    'SFO Airport': set(['San Bruno', 'Millbrae']),
    'Millbrae': set(['SFO Airport', 'San Bruno']),
    'Asby': set(['MacArthur', 'Downtown Berkeley']),
    'Downtown Berkeley': set(['Asby', 'North Berkeley']),
    'North Berkeley': set(['Downtown Berkeley', 'El Cerrito Plazza']),
    'El Cerrito Plazza': set(['North Berkeley', 'El Cerrito del Norte']),
    'El Cerrito del Norte': set(['El Cerrito Plazza', 'Richmond']),
    'Richmond': set(['El Cerrito del Norte']),
    'Lake Merritt': set(['12th St/Oakland City Center', 'West Oakland', 'Fruitvale']),
    'Fruitvale': set(['Lake Merritt', 'Coliseum']),
    'Coliseum': set(['Fruitvale', 'Oakland Airport', 'San Leandro']),
    'Oakland Airport': set(['Coliseum']),
    'San Leandro': set(['Coliseum', 'Bay Fair']),
    'Bay Fair': set(['San Leandro', 'Castro Valley', 'Hayward']),
    'Hayward': set(['Bay Fair', 'South Hayward']),
    'South Hayward': set(['Hayward', 'Union City']),
    'Union City': set(['South Hayward', 'Fremont']),
    'Fremont': set(['Union City', 'Warm Springs/South Fremont']),
    'Warm Springs/South Fremont': set(['Fremont', 'Milpitas']),
    'Milpitas': set(['Warm Springs/South Fremont', 'Berryessa/North San Jose']),
    'Berryessa/North San Jose': set(['Milpitas']),
    'Castro Valley': set(['Bay Fair', 'West Dublin/Pleasanton']),
    'West Dublin/Pleasanton': set(['Castro Valley', 'Dublin/Pleasanton']),
    'Dublin/Pleasanton': set(['West Dublin/Pleasanton']),

}
